
# 1. Data preprocessing

In [1]:
#Import of header files
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') 
from sklearn import metrics
from sklearn.metrics import classification_report

In [2]:
#Reading the file
data=pd.read_csv("Dataset.csv")

In [3]:
#First five records
data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        0          0                     0                    1          1   
1        0          0                     0                    0          1   
2        0          0                     0                    1          0   
3        0          0                     0                    1          1   
4        0          0                     0                    1          1   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       1           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       1           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       1           0             0        0                 0  ...   

   painful_walking  pus_filled_pimples  scurring  skin_peeling  \
0                0                   0         0             0   
1                0                   0         0             0   
2                0                   0         0             0   
3                0                   0         0             0   
4                0                   0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   yellow_crust_ooze  prognosis  
0                  0    Allergy  
1                  0    Allergy  
2                  0    Allergy  
3                  0    Allergy  
4                  0    Allergy  

[5 rows x 128 columns]

In [4]:
#Target values
data['prognosis'].unique()

array(['Allergy', 'Common Cold', 'Dengue', 'Diabetes ', 'Hepatitis C',
       'Hepatitis E', 'Malaria', 'Tuberculosis', 'Typhoid'], dtype=object)

In [5]:
#Taking the target data
y=data['prognosis']
y.head()

0    Allergy
1    Allergy
2    Allergy
3    Allergy
4    Allergy
Name: prognosis, dtype: object

In [6]:

#Creating the temporary dataframe
temp=data
#Deleting the target column from the temp dataframe
del temp['prognosis']

In [7]:
#Getting the X value or feature value in x
x=temp

In [8]:
#First five value of x
x.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        0          0                     0                    1          1   
1        0          0                     0                    0          1   
2        0          0                     0                    1          0   
3        0          0                     0                    1          1   
4        0          0                     0                    1          1   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       1           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       1           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       1           0             0        0                 0  ...   

   palpitations  painful_walking  pus_filled_pimples  scurring  skin_peeling  \
0             0                0                   0         0             0   
1             0                0                   0         0             0   
2             0                0                   0         0             0   
3             0                0                   0         0             0   
4             0                0                   0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   yellow_crust_ooze  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 127 columns]

In [9]:
#Name of the columns of x
x.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'palpitations', 'painful_walking', 'pus_filled_pimples', 'scurring',
       'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails',
       'inflammatory_nails', 'blister', 'yellow_crust_ooze'],
      dtype='object', length=127)

In [10]:
#Shape of the x and y
x.shape,y.shape

((1080, 127), (1080,))

In [11]:
#Describe of the x data
x.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count   1080.0  1080.000000                1080.0          1080.000000   
mean       0.0     0.105556                   0.0             0.205556   
std        0.0     0.307410                   0.0             0.404294   
min        0.0     0.000000                   0.0             0.000000   
25%        0.0     0.000000                   0.0             0.000000   
50%        0.0     0.000000                   0.0             0.000000   
75%        0.0     0.000000                   0.0             0.000000   
max        0.0     1.000000                   0.0             1.000000   

         shivering       chills   joint_pain  stomach_pain  acidity  \
count  1080.000000  1080.000000  1080.000000        1080.0   1080.0   
mean      0.100000     0.633333     0.211111           0.0      0.0   
std       0.300139     0.482118     0.408286           0.0      0.0   
min       0.000000     0.000000     0.000000           0.0      0.0   
25%       0.000000     0.000000     0.000000           0.0      0.0   
50%       0.000000     1.000000     0.000000           0.0      0.0   
75%       0.000000     1.000000     0.000000           0.0      0.0   
max       1.000000     1.000000     1.000000           0.0      0.0   

       ulcers_on_tongue  ...  palpitations  painful_walking  \
count            1080.0  ...        1080.0           1080.0   
mean                0.0  ...           0.0              0.0   
std                 0.0  ...           0.0              0.0   
min                 0.0  ...           0.0              0.0   
25%                 0.0  ...           0.0              0.0   
50%                 0.0  ...           0.0              0.0   
75%                 0.0  ...           0.0              0.0   
max                 0.0  ...           0.0              0.0   

       pus_filled_pimples  scurring  skin_peeling  silver_like_dusting  \
count              1080.0    1080.0        1080.0               1080.0   
mean                  0.0       0.0           0.0                  0.0   
std                   0.0       0.0           0.0                  0.0   
min                   0.0       0.0           0.0                  0.0   
25%                   0.0       0.0           0.0                  0.0   
50%                   0.0       0.0           0.0                  0.0   
75%                   0.0       0.0           0.0                  0.0   
max                   0.0       0.0           0.0                  0.0   

       small_dents_in_nails  inflammatory_nails  blister  yellow_crust_ooze  
count                1080.0              1080.0   1080.0             1080.0  
mean                    0.0                 0.0      0.0                0.0  
std                     0.0                 0.0      0.0                0.0  
min                     0.0                 0.0      0.0                0.0  
25%                     0.0                 0.0      0.0                0.0  
50%                     0.0                 0.0      0.0                0.0  
75%                     0.0                 0.0      0.0                0.0  
max                     0.0                 0.0      0.0                0.0  

[8 rows x 127 columns]

In [12]:
#Getting the column with number of unique value they are having
nunique = x.apply(pd.Series.nunique)
#First five column name
nunique.head()

itching                 1
skin_rash               2
nodal_skin_eruptions    1
continuous_sneezing     2
shivering               2
dtype: int64

In [13]:
#list of columns with same value in all the rows
cols_to_drop = nunique[nunique == 1].index
cols_to_drop

Index(['itching', 'nodal_skin_eruptions', 'stomach_pain', 'acidity',
       'ulcers_on_tongue', 'weight_gain', 'anxiety', 'cold_hands_and_feets',
       'mood_swings', 'patches_in_throat', 'sunken_eyes', 'dehydration',
       'indigestion', 'yellow_urine', 'fluid_overload', 'swelling_of_stomach',
       'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bowel_movements',
       'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus',
       'neck_pain', 'dizziness', 'cramps', 'bruising', 'swollen_legs',
       'swollen_blood_vessels', 'puffy_face_and_eyes', 'enlarged_thyroid',
       'brittle_nails', 'swollen_extremeties', 'extra_marital_contacts',
       'drying_and_tingling_lips', 'slurred_speech', 'knee_pain',
       'hip_joint_pain', 'muscle_weakness', 'stiff_neck', 'swelling_joints',
       'movement_stiffness', 'spinning_movements', 'loss_of_balance',
       'unsteadiness', 'weakness_of_one_body_side', 'bladder_discomfort',
       'foul_smell_of urine', 'continuous_feel_of_

In [14]:
#Removing the columns with the same value in all the records
x_filter=x.drop(cols_to_drop, axis=1)

In [15]:
#First five records of x_filter
x_filter.head()

skin_rash  continuous_sneezing  shivering  chills  joint_pain  vomiting  \
0          0                    1          1       1           0         0   
1          0                    0          1       1           0         0   
2          0                    1          0       1           0         0   
3          0                    1          1       0           0         0   
4          0                    1          1       1           0         0   

   fatigue  weight_loss  restlessness  lethargy  ...  muscle_pain  \
0        0            0             0         0  ...            0   
1        0            0             0         0  ...            0   
2        0            0             0         0  ...            0   
3        0            0             0         0  ...            0   
4        0            0             0         0  ...            0   

   red_spots_over_body  belly_pain  watering_from_eyes  increased_appetite  \
0                    0           0                   1                   0   
1                    0           0                   1                   0   
2                    0           0                   1                   0   
3                    0           0                   1                   0   
4                    0           0                   0                   0   

   polyuria  family_history  coma  stomach_bleeding  blood_in_sputum  
0         0               0     0                 0                0  
1         0               0     0                 0                0  
2         0               0     0                 0                0  
3         0               0     0                 0                0  
4         0               0     0                 0                0  

[5 rows x 52 columns]

In [16]:
#Describe fun for x_filter
x_filter.describe()

skin_rash  continuous_sneezing    shivering       chills  \
count  1080.000000          1080.000000  1080.000000  1080.000000   
mean      0.105556             0.205556     0.100000     0.633333   
std       0.307410             0.404294     0.300139     0.482118   
min       0.000000             0.000000     0.000000     0.000000   
25%       0.000000             0.000000     0.000000     0.000000   
50%       0.000000             0.000000     0.000000     1.000000   
75%       0.000000             0.000000     0.000000     1.000000   
max       1.000000             1.000000     1.000000     1.000000   

        joint_pain     vomiting      fatigue  weight_loss  restlessness  \
count  1080.000000  1080.000000  1080.000000  1080.000000   1080.000000   
mean      0.211111     0.527778     0.744444     0.211111      0.105556   
std       0.408286     0.499459     0.436375     0.408286      0.307410   
min       0.000000     0.000000     0.000000     0.000000      0.000000   
25%       0.000000     0.000000     0.000000     0.000000      0.000000   
50%       0.000000     1.000000     1.000000     0.000000      0.000000   
75%       0.000000     1.000000     1.000000     0.000000      0.000000   
max       1.000000     1.000000     1.000000     1.000000      1.000000   

          lethargy  ...  muscle_pain  red_spots_over_body   belly_pain  \
count  1080.000000  ...  1080.000000          1080.000000  1080.000000   
mean      0.105556  ...     0.327778             0.105556     0.105556   
std       0.307410  ...     0.469621             0.307410     0.307410   
min       0.000000  ...     0.000000             0.000000     0.000000   
25%       0.000000  ...     0.000000             0.000000     0.000000   
50%       0.000000  ...     0.000000             0.000000     0.000000   
75%       0.000000  ...     1.000000             0.000000     0.000000   
max       1.000000  ...     1.000000             1.000000     1.000000   

       watering_from_eyes  increased_appetite     polyuria  family_history  \
count         1080.000000         1080.000000  1080.000000     1080.000000   
mean             0.100000            0.111111     0.111111        0.105556   
std              0.300139            0.314415     0.314415        0.307410   
min              0.000000            0.000000     0.000000        0.000000   
25%              0.000000            0.000000     0.000000        0.000000   
50%              0.000000            0.000000     0.000000        0.000000   
75%              0.000000            0.000000     0.000000        0.000000   
max              1.000000            1.000000     1.000000        1.000000   

              coma  stomach_bleeding  blood_in_sputum  
count  1080.000000       1080.000000      1080.000000  
mean      0.111111          0.111111         0.111111  
std       0.314415          0.314415         0.314415  
min       0.000000          0.000000         0.000000  
25%       0.000000          0.000000         0.000000  
50%       0.000000          0.000000         0.000000  
75%       0.000000          0.000000         0.000000  
max       1.000000          1.000000         1.000000  

[8 rows x 52 columns]

In [17]:
#Shape of x and  x_filter
x.shape,x_filter.shape

((1080, 127), (1080, 52))

In [18]:
""'Now we can see that the number of columns reduce to 52 from 127""'
""'We will take all the cases as of taking the x as data and x_filter as data and on basis of accuracy final x will be decided ""';

In [19]:
#Import train_test_split
from sklearn.model_selection import train_test_split

In [20]:
#Taking the whole data 
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.3)

In [21]:
x_train.shape,y_train.shape

((756, 127), (756,))

In [22]:
#Taking x_filter
x_train_filter,x_test_filter,y_train_filter,y_test_filter=train_test_split(x_filter,y,random_state=0,test_size=0.3)

In [23]:
x_train_filter.shape,y_train_filter.shape

((756, 52), (756,))

# 2. Feature Selection 

In [24]:
#Scaling the the whole data, as linear models benefits from feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train.fillna(0))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
#Scaling the the filter data
scaler_filter = StandardScaler()
scaler_filter.fit(x_train_filter.fillna(0))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [26]:
''' In all feature selection procedures, it is a good practice to select the features by examining only the training set.
This is to avoid overfitting.''';

In [27]:
#Import select_from_model
from sklearn.feature_selection import SelectFromModel

In [28]:
#Selecting features using Lasso regularisation using SelectFromModel
from sklearn.linear_model import Lasso

# 2.1 Using Logistic Regression with Lasso

In [29]:
'''Here I will do the model fitting and feature selection, altogether in one line of code.
First I specify the Logistic Regression model, and I make sure I select the Lasso (L1) penalty.
Then I use the selectFromModel object from sklearn, which will select in theory the features which coefficients are non-zero.''';

In [30]:
#Importing the Logistic Regression
import sklearn.linear_model as lm

In [31]:
#For whole data
#  SelectFromModel(estimator=LogisticRegression())
#sel_ =lm.LogisticRegression(C=1, penalty='l1', solver='liblinear')
sel_ =SelectFromModel(estimator=lm.LogisticRegression(C=1, penalty='l1', solver='liblinear'))
sel_.fit(scaler.transform(x_train.fillna(0)), y_train)

SelectFromModel(estimator=LogisticRegression(C=1, class_weight=None, dual=False,
                                             fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='auto',
                                             n_jobs=None, penalty='l1',
                                             random_state=None,
                                             solver='liblinear', tol=0.0001,
                                             verbose=0, warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [32]:
#For filter data
sel_filter = SelectFromModel(estimator=lm.LogisticRegression(C=1, penalty='l1', solver='liblinear'))
sel_filter.fit(scaler_filter.transform(x_train_filter.fillna(0)), y_train)

SelectFromModel(estimator=LogisticRegression(C=1, class_weight=None, dual=False,
                                             fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='auto',
                                             n_jobs=None, penalty='l1',
                                             random_state=None,
                                             solver='liblinear', tol=0.0001,
                                             verbose=0, warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [33]:
#Visualising features of whole data that were kept by the lasso regularisation
sel_.get_support()

array([False,  True, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False,  True, False,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False, False, False, False, False, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [34]:
#Visualising features of filter data that were kept by the lasso regularisation
sel_filter.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
       False,  True, False,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True, False,  True,  True, False,
       False, False,  True, False, False,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [35]:
'''In the above output, the output labels are index wise. 
So True is for the features that lasso thought is important (non-zero features)
while False is for the features whose weights were shrinked to zero and are not important according to Lasso.''';

In [36]:
# Make a list of with the selected features from whole data.
selected_feat = x_train.columns[(sel_.get_support())]
print('total features: {}'.format((x_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 127
selected features: 32
features with coefficients shrank to zero: 1106


In [37]:
#Number of features which coefficient was shrank to zero in whole data
np.sum(sel_.estimator_.coef_ == 0)

1106

In [39]:
# Make a list of with the selected features for filter data.
selected_feat_filter = x_train_filter.columns[(sel_filter.get_support())]
print('total features: {}'.format((x_train_filter.shape[1])))
print('selected features: {}'.format(len(selected_feat_filter)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_filter.estimator_.coef_ == 0)))

total features: 52
selected features: 33
features with coefficients shrank to zero: 429


In [40]:
#Number of features which coefficient was shrank to zero in filter data
np.sum(sel_filter.estimator_.coef_ == 0)

429

In [41]:
"""It can be seen from above that number of selected features 
in both whole data and filter data are somehow close to each other.""";

In [42]:
#Removing the features from training and test set for whole data
x_train_selected = sel_.transform(x_train.fillna(0))
x_test_selected = sel_.transform(x_test.fillna(0))
x_train_selected.shape, x_test_selected.shape

((756, 32), (324, 32))

In [43]:
#Value in x_train_selected
x_train_selected

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0]])

In [44]:
#Removing the features from training and test set for filter data
x_train_selected_filter = sel_filter.transform(x_train_filter.fillna(0))
x_test_selected_filter = sel_filter.transform(x_test_filter.fillna(0))
x_train_selected_filter.shape, x_test_selected_filter.shape

((756, 33), (324, 33))

In [45]:
#value in x_train_selected_filter
x_train_selected_filter

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0]])

# 2.2 Using Random Forest

In [46]:
#Importing the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

In [47]:
'''Here I will do the model fitting and feature selection altogether in one line of code.
Firstly, I specify the random forest instance, indicating the number of trees.
Then I use selectFromModel object from sklearn to automatically select the features''';

In [48]:
#For whole data
sel_1 = SelectFromModel(RandomForestClassifier(n_estimators = 100))
sel_1.fit(x_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,

In [49]:
#For filter data
sel_1_filter = SelectFromModel(RandomForestClassifier(n_estimators = 100))
sel_1_filter.fit(x_train_filter, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,

In [50]:
#Removing the feature from whole data
x_train_selected_1 = sel_1.transform(x_train.fillna(0))
x_test_selected_1 = sel_1.transform(x_test.fillna(0))
x_train_selected_1.shape, x_test_selected_1.shape

((756, 49), (324, 49))

In [51]:
#Removing the feature from filter data
x_train_selected_1_filter = sel_1_filter.transform(x_train_filter.fillna(0))
x_test_selected_1_filter = sel_1_filter.transform(x_test_filter.fillna(0))
x_train_selected_1_filter.shape, x_test_selected_1_filter.shape

((756, 23), (324, 23))

# 2.3 Using PCA(Principal Component Analysis)

In [52]:
#Importing the PCA
from sklearn.decomposition import PCA 

In [53]:
pca = PCA()

In [54]:
#Tranformation over whole data
x_transformed_train = pca.fit_transform(x_train,y)
x_transformed_test = pca.fit_transform(x_test,y)

In [55]:
x_transformed_train

array([[-2.13435294e-01, -1.45543796e+00, -2.72104635e-01, ...,
         2.01124082e-15, -0.00000000e+00, -0.00000000e+00],
       [ 2.94127971e+00,  3.38516024e-01, -4.46466649e-01, ...,
        -2.62364331e-17, -3.01881523e-16, -1.83649059e-16],
       [-1.34463069e+00, -7.90142962e-01,  1.32707773e+00, ...,
         3.92879527e-17,  7.65845352e-16, -1.90625695e-16],
       ...,
       [-9.49803789e-02, -7.95602144e-01, -1.10668640e+00, ...,
        -6.65440418e-18, -1.85635260e-17, -1.36296734e-17],
       [-1.14054795e+00,  2.12026543e-01,  6.62988733e-01, ...,
         7.64199862e-18,  1.16599057e-17,  7.27201472e-18],
       [-1.53745111e+00, -1.09682612e+00,  1.24176533e+00, ...,
         9.98667132e-20, -6.34097572e-18,  6.41145714e-18]])

In [56]:
#Tranformation over filter data
x_transformed_train_filter=pca.fit_transform(x_train_filter,y)
x_transformed_test_filter=pca.fit_transform(x_test_filter,y)

In [57]:
x_transformed_train_filter

array([[-2.13435294e-01, -1.45543796e+00, -2.72104635e-01, ...,
        -3.84009951e-18,  1.83201594e-17,  2.58969819e-17],
       [ 2.94127971e+00,  3.38516024e-01, -4.46466649e-01, ...,
        -5.59792853e-17,  1.86385073e-18, -1.87282075e-17],
       [-1.34463069e+00, -7.90142962e-01,  1.32707773e+00, ...,
         8.28728105e-17,  4.88161525e-17,  3.51275429e-16],
       ...,
       [-9.49803789e-02, -7.95602144e-01, -1.10668640e+00, ...,
        -7.61602144e-17,  8.45665117e-17, -8.83790572e-18],
       [-1.14054795e+00,  2.12026543e-01,  6.62988733e-01, ...,
        -4.87585094e-17,  3.69293963e-18, -3.91606829e-18],
       [-1.53745111e+00, -1.09682612e+00,  1.24176533e+00, ...,
         9.84993900e-18,  4.48399002e-17,  2.78973544e-18]])

# 3. Training and Testing over Different Algorithms

# 3.1 Random Forest Classifier

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
#Classifier for whole data tranfrom from Lasso Feature selection
clf_random_lasso = RandomForestClassifier(max_depth=2,random_state=0)

In [60]:
#Training the model
clf_random_lasso.fit(x_train_selected, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [61]:
#Taking prediction from the model
y_predict_random_lasso=clf_random_lasso.predict(x_test_selected)

In [62]:
print(classification_report(y_test, y_predict_random_lasso))

              precision    recall  f1-score   support

     Allergy       1.00      1.00      1.00        32
 Common Cold       1.00      1.00      1.00        26
      Dengue       1.00      1.00      1.00        39
   Diabetes        1.00      1.00      1.00        38
 Hepatitis C       1.00      1.00      1.00        37
 Hepatitis E       1.00      1.00      1.00        42
     Malaria       1.00      1.00      1.00        34
Tuberculosis       1.00      1.00      1.00        36
     Typhoid       1.00      1.00      1.00        40

    accuracy                           1.00       324
   macro avg       1.00      1.00      1.00       324
weighted avg       1.00      1.00      1.00       324



In [63]:
'''What I can do, is decide that I'm not interested in the scores of labels that were not predicted, 
and then explicitly specify the labels which are in our interest (which are labels that were predicted at least once):'''

metrics.f1_score(y_test, y_predict_random_lasso, average='weighted', labels=np.unique(y_predict_random_lasso))

1.0

In [64]:
'''Doing the same thing for filter data in Lasso Regularization'''

'Doing the same thing for filter data in Lasso Regularization'

In [65]:
#Classification for Random forest from Lasso Regularisation 
clf_random_lasso_filter = RandomForestClassifier(max_depth=2,random_state=0)

In [66]:
clf_random_lasso_filter.fit(x_train_selected_filter, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [67]:
y_predict_random_lasso_filter=clf_random_lasso_filter.predict(x_test_selected_filter)

In [68]:
print(classification_report(y_test, y_predict_random_lasso_filter))

              precision    recall  f1-score   support

     Allergy       1.00      1.00      1.00        32
 Common Cold       1.00      1.00      1.00        26
      Dengue       1.00      1.00      1.00        39
   Diabetes        1.00      1.00      1.00        38
 Hepatitis C       1.00      1.00      1.00        37
 Hepatitis E       1.00      1.00      1.00        42
     Malaria       1.00      1.00      1.00        34
Tuberculosis       1.00      1.00      1.00        36
     Typhoid       1.00      1.00      1.00        40

    accuracy                           1.00       324
   macro avg       1.00      1.00      1.00       324
weighted avg       1.00      1.00      1.00       324



In [69]:
metrics.f1_score(y_test,y_predict_random_lasso_filter, average='weighted', labels=np.unique(y_predict_random_lasso_filter))

1.0

In [70]:
"""From above we had find the two score Using Lasso Regularisation and Using Random Forest Classifier with whole data and our filter data.
And we can see that accuracy is almost same somehow.""";

In [71]:
'''Using PCA Transform data in Random Forest''';

In [72]:
#Classifier of Random forest Classifier with PCA for whole data
clf_pca = RandomForestClassifier(max_depth=5,random_state=0)

In [73]:
clf_pca.fit(x_transformed_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [74]:
y_pca=clf_pca.predict(x_transformed_test)

In [75]:
print(classification_report(y_test, y_pca))

              precision    recall  f1-score   support

     Allergy       1.00      0.50      0.67        32
 Common Cold       1.00      0.85      0.92        26
      Dengue       0.40      0.74      0.52        39
   Diabetes        0.48      0.37      0.42        38
 Hepatitis C       0.25      0.22      0.23        37
 Hepatitis E       0.00      0.00      0.00        42
     Malaria       0.39      1.00      0.56        34
Tuberculosis       0.92      1.00      0.96        36
     Typhoid       0.50      0.23      0.31        40

    accuracy                           0.52       324
   macro avg       0.55      0.54      0.51       324
weighted avg       0.52      0.52      0.48       324



In [76]:
metrics.f1_score(y_test,y_pca, average='weighted', labels=np.unique(y_pca))

0.480703750535579

In [77]:
#Evaluting with the Filter data
clf_pca_filter= RandomForestClassifier(max_depth=5,random_state=0)
clf_pca_filter.fit(x_transformed_train_filter,y_train)
y_pca_filter=clf_pca_filter.predict(x_transformed_test_filter)

In [78]:
print(classification_report(y_test, y_pca_filter))

              precision    recall  f1-score   support

     Allergy       1.00      0.69      0.81        32
 Common Cold       0.81      1.00      0.90        26
      Dengue       0.72      0.72      0.72        39
   Diabetes        0.54      0.39      0.45        38
 Hepatitis C       0.57      0.84      0.68        37
 Hepatitis E       0.94      0.74      0.83        42
     Malaria       0.44      1.00      0.61        34
Tuberculosis       1.00      1.00      1.00        36
     Typhoid       1.00      0.05      0.10        40

    accuracy                           0.69       324
   macro avg       0.78      0.71      0.68       324
weighted avg       0.78      0.69      0.66       324



In [79]:
metrics.f1_score(y_test,y_pca_filter, average='weighted', labels=np.unique(y_pca_filter))

0.6636985133813571

In [80]:
'''From above two score it can be seen that when,
we use pca with random forest then filter data shows some high accuracy but not upto the mark.''';

# 3.2 Support Vector Machine(SVM)

In [81]:
#import of the Library
from sklearn.svm import SVC
clf_SVM=SVC(probability=True)

**Features that we have selected**

In [82]:
print(selected_feat_filter.shape)
selected_feat_filter

(33,)


Index(['skin_rash', 'continuous_sneezing', 'shivering', 'fatigue',
       'irregular_sugar_level', 'high_fever', 'breathlessness', 'sweating',
       'yellowish_skin', 'nausea', 'pain_behind_the_eyes', 'back_pain',
       'constipation', 'diarrhoea', 'mild_fever', 'malaise',
       'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose',
       'congestion', 'loss_of_smell', 'toxic_look_(typhos)', 'muscle_pain',
       'red_spots_over_body', 'belly_pain', 'watering_from_eyes',
       'increased_appetite', 'polyuria', 'family_history', 'coma',
       'stomach_bleeding', 'blood_in_sputum'],
      dtype='object')

array(['Allergy', 'Common Cold', 'Dengue', 'Diabetes ', 'Hepatitis C',
       'Hepatitis E', 'Malaria', 'Tuberculosis', 'Typhoid'], dtype=object)

In [83]:
clf_SVM.fit(x_train_selected_filter, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [84]:
y_test_SVM=clf_SVM.predict(x_test_selected_filter)
y_test_SVM[:10]

array(['Tuberculosis', 'Tuberculosis', 'Hepatitis E', 'Hepatitis C',
       'Hepatitis E', 'Typhoid', 'Typhoid', 'Common Cold', 'Hepatitis C',
       'Diabetes '], dtype=object)

In [85]:
print(classification_report(y_test, y_test_SVM))

              precision    recall  f1-score   support

     Allergy       1.00      1.00      1.00        32
 Common Cold       1.00      1.00      1.00        26
      Dengue       1.00      1.00      1.00        39
   Diabetes        1.00      1.00      1.00        38
 Hepatitis C       1.00      1.00      1.00        37
 Hepatitis E       1.00      1.00      1.00        42
     Malaria       1.00      1.00      1.00        34
Tuberculosis       1.00      1.00      1.00        36
     Typhoid       1.00      1.00      1.00        40

    accuracy                           1.00       324
   macro avg       1.00      1.00      1.00       324
weighted avg       1.00      1.00      1.00       324



In [86]:
import pickle

In [87]:
with open("./model.pkl", 'wb') as f:
    pickle.dump(clf_SVM,f)

In [88]:
with open("./model.pkl", 'rb') as f:
    clf_SVM = pickle.load(f)

In [89]:
'''So it can be seen that with SVM the score is coming to be more accurate than Random Forest Classifier''';

'''We will for now give the output for those only whose probability is more than 40%(After Checking against many test cases), 
rest if less than we request to fill the form again''';

## Checking for some symptons based on the data provided by the google

'''Like for Diabetes the Symptons are'''
Excessive thirst and hunger
Frequent urination (from urinary tract infections or kidney problems)
Weight loss or gain
Fatigue
Irritability
Blurred vision
Slow-healing wounds
Nausea

In [90]:
'''Tested Data based on the symptons information from the 
google(https://www.medicinenet.com/diabetes_symptoms_in_men/article.htm)'''
check=np.array([[0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0]])
check.shape

(1, 33)

skin_rash', 'continuous_sneezing', 'shivering', 'fatigue',
       'high_fever', 'sweating', 'yellowish_skin', 'dark_urine', 'nausea',
       'pain_behind_the_eyes', 'back_pain', 'constipation', 'diarrhoea',
       'mild_fever', 'malaise', 'throat_irritation', 'redness_of_eyes',
       'sinus_pressure', 'runny_nose', 'congestion', 'loss_of_smell',
       'toxic_look_(typhos)', 'muscle_pain', 'red_spots_over_body',
       'belly_pain', 'watering_from_eyes', 'increased_appetite', 'polyuria',
       'family_history', 'coma', 'stomach_bleeding', 'blood_in_sputum'

In [91]:
# Probability of all the Classes
check_array=clf_SVM.predict_proba(check)
check_array

array([[0.09209724, 0.04325098, 0.04929386, 0.10576074, 0.23219343,
        0.07763653, 0.08251223, 0.04920341, 0.26805157]])

In [92]:
# Predictions
check_output=clf_SVM.predict(check)
check_output

array(['Typhoid'], dtype=object)

In [93]:
Diseases=['Allergy', 'Common Cold', 'Dengue', 'Diabetes ', 'Hepatitis C',
       'Hepatitis E', 'Malaria', 'Tuberculosis', 'Typhoid']
print((check_array[0]))
print(np.amax(check_array[0]))
print(np.where(check_array==np.amax(check_array[0])))

[0.09209724 0.04325098 0.04929386 0.10576074 0.23219343 0.07763653
 0.08251223 0.04920341 0.26805157]
0.2680515704641207
(array([0]), array([8]))


In [94]:
'''Validating the Conditions'''
for i in range(len(check_array)):
    if max(check_array[i])<0.40:
        print("PLEASE CHECK THE SYMPTOMS AGAIN")
    else:
        print(check_output[0])
    

PLEASE CHECK THE SYMPTOMS AGAIN


In [95]:
'''If some data point look like this'''
check2=np.array([[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
check2.shape

(1, 33)

In [96]:
#Probability of all Classes
check2_array=clf_SVM.predict_proba(check2)
check2_array

array([[0.11058477, 0.1222261 , 0.11487097, 0.10093889, 0.10526849,
        0.11123622, 0.11728602, 0.11175077, 0.10583777]])

In [97]:
# Predictions
check2_output=clf_SVM.predict(check2)
check2_output

array(['Dengue'], dtype=object)

In [98]:
'''Validating the Conditions'''
for i in range(len(check2_array)):
    if max(check2_array[i])<0.40:
        print("PLEASE CHECK THE SYMPTOMS AGAIN")
    else:
        print(check_output[0])

PLEASE CHECK THE SYMPTOMS AGAIN


"Here Even the Model is Giving the Output to be Common Cold but We will go again for Symptoms Check"

skin_rash', 'continuous_sneezing', 'shivering', 'fatigue', 'high_fever', 'sweating', 'yellowish_skin', 'dark_urine', 'nausea', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'diarrhoea', 'mild_fever', 'malaise', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'loss_of_smell', 'toxic_look_(typhos)', 'muscle_pain', 'red_spots_over_body', 'belly_pain', 'watering_from_eyes', 'increased_appetite', 'polyuria', 'family_history', 'coma', 'stomach_bleeding', 'blood_in_sputum

In [99]:
op=np.array([[0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]])

In [100]:
pp=clf_SVM.predict_proba(op)

In [101]:
'''Validating the Conditions'''
for i in range(len(pp)):
    if max(check2_array[i])<0.40:
        print("PLEASE CHECK THE SYMPTOMS AGAIN")
    else:
        print(check_output[0])

PLEASE CHECK THE SYMPTOMS AGAIN
